development:
  adapter: postgresql
  encoding: unicode
  database: fc_randomizer_development
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: fc_randomizer_production
  pool: 5
